name:                bigtrees
description:         Performant hash trees to dedup large collections of files.
version:             1.0.0.0
author:              jefdaj
maintainer:          jefdaj@users.noreply.github.com
copyright:           "AGPL-3.0-only"

dependencies:
  # - -- cryptohash
  # - ansi-terminal
  # - byteable
  # - directory-tree
  # - hspec
  # - pretty-simple
  # - process
  # - tasty
  # - tasty-discover
  # - tasty-hunit
  # - tasty-quickcheck
  # - text
  # - with-utf8
  - Glob
  - HUnit
  - MissingH
  - QuickCheck
  - attoparsec
  - base
  - base64-bytestring
  - bytestring
  - crypton
  - deepseq
  - directory
  - filepath
  - hashable
  - hashtables
  - massiv
  - monad-parallel
  - quickcheck-instances
  - quickcheck-unicode
  - safe-exceptions
  - split
  - store
  - streaming
  - streaming-bytestring
  - system-filepath
  - tasty
  - tasty-discover
  - tasty-hspec
  - tasty-hunit
  - tasty-quickcheck
  - temporary
  - text
  - th-utilities
  - unix
  - unordered-containers
  - utf8-string
 
library:
  source-dirs: lib
  exposed-modules:
  - System.Directory.BigTrees
  - System.Directory.BigTrees.DupeMap
  - System.Directory.BigTrees.HashTree
  - System.Directory.BigTrees.HashForest
  - System.Directory.BigTrees.HashLine
  - System.Directory.BigTrees.Util
  - System.Directory.BigTrees.Hash
  - System.Directory.BigTrees.Delta
  # System.Directory.Tree

executable:
  source-dirs: app
  main: BigTrees.hs
  # TODO which of these options really help?
  ghc-options: "-Wall -O2 -threaded -rtsopts -with-rtsopts=-N"
  dependencies:
  - bigtrees
  - pretty-simple
  - setlocale
  - docopt

tests:
  test-lib:
    source-dirs:
    - "lib"
    - "test/lib"
    main: "Test.hs"
    # TODO which of these options really help?
    ghc-options: "-Wall -O2 -threaded -rtsopts -with-rtsopts=-N"
    dependencies:
    - bigtrees
