name:                bigtrees
description:         Performant hash trees to dedup large collections of files.
version:             1.0.0.0
author:              jefdaj
maintainer:          jefdaj@users.noreply.github.com
copyright:           "AGPL-3.0-only"

# data-files:
#   - examples/*.sh
#   - examples/*.txt

dependencies:
  - Glob
  - base
  - bytestring
  - crypton
  - deepseq
  - directory
  - filepath
  - hashable
  - hashtables
  - massiv
  - monad-parallel
  - quickcheck-instances
  - quickcheck-unicode
  - safe-exceptions
  - split
  - store
  - streaming
  - streaming-bytestring
  - system-filepath
  - tasty
  - tasty-discover
  - tasty-golden
  - tasty-hspec
  - tasty-hunit
  - tasty-quickcheck
  - temporary
  - text
  - th-utilities
  - unix
  - unordered-containers
  - utf8-string
 
library:
  source-dirs: lib
  exposed-modules:
  - System.Directory.BigTrees
  - System.Directory.BigTrees.DupeMap
  - System.Directory.BigTrees.HashTree
  - System.Directory.BigTrees.HashForest
  - System.Directory.BigTrees.HashLine
  - System.Directory.BigTrees.Util
  - System.Directory.BigTrees.Hash
  - System.Directory.BigTrees.Delta
  # System.Directory.Tree
  dependencies:
  - HUnit
  - MissingH
  - QuickCheck
  - attoparsec
  - base64-bytestring

executable:
  source-dirs: app
  main: Main.hs
  # TODO which of these options really help?
  ghc-options: "-Wall -O2 -threaded -rtsopts -with-rtsopts=-N -fwrite-ide-info"
  dependencies:
  - bigtrees
  - pretty-simple
  - setlocale
  - docopt
  - unbounded-delays
  - silently
  - process

tests:

  test-lib:
    source-dirs:
    - "lib"
    - "test/lib"
    main: "Test.hs"
    # TODO which of these options really help?
    # ghc-options: "-Wall -O2 -threaded -rtsopts -with-rtsopts=-N -fwrite-ide-info"
    ghc-options:
    - "-O2"
    - "-threaded"
    - "-rtsopts"
    - "-with-rtsopts=-N"
    - "-fwrite-ide-info"
    - "-hiedir=.hie"
    - "-Wall"
    - "-Wcompat"
    - "-Widentities"
    - "-Wincomplete-uni-patterns"
    - "-Wincomplete-record-updates"
    - "-Wredundant-constraints"
    - "-Wmissing-export-lists"
    - "-Wpartial-fields"
    - "-Wmissing-deriving-strategies"
    - "-Wunused-packages"
    dependencies:
    - bigtrees
    - HUnit
    - MissingH
    - QuickCheck
    - attoparsec
    - base64-bytestring

  test-app:
    source-dirs:
    - "test/app"
    - "app"
    main: "Test.hs"
    # TODO which of these options really help?
    # ghc-options: "-Wall -O2 -threaded -rtsopts -with-rtsopts=-N -fwrite-ide-info"
    ghc-options:
    - "-O2"
    - "-threaded"
    - "-rtsopts"
    - "-with-rtsopts=-N"
    - "-fwrite-ide-info"
    - "-hiedir=.hie"
    - "-Wall"
    - "-Wcompat"
    - "-Widentities"
    - "-Wincomplete-uni-patterns"
    - "-Wincomplete-record-updates"
    - "-Wredundant-constraints"
    - "-Wmissing-export-lists"
    - "-Wpartial-fields"
    - "-Wmissing-deriving-strategies"
    - "-Wunused-packages"
    # TODO extract a common list of exe dependencies
    dependencies:
    - pretty-simple
    - setlocale
    - docopt
    - bigtrees
    - unbounded-delays
    - silently
    - process

  test-doctests:
    source-dirs:
    - "test/doc"
    - "lib"
    - "app"
    main: "doctest.hs"
    # TODO which of these options really help?
    # ghc-options: "-Wall -O2 -threaded -rtsopts -with-rtsopts=-N -fwrite-ide-info"
    ghc-options:
    - "-O2"
    - "-threaded"
    - "-rtsopts"
    - "-with-rtsopts=-N"
    - "-fwrite-ide-info"
    - "-hiedir=.hie"
    - "-Wall"
    - "-Wcompat"
    - "-Widentities"
    - "-Wincomplete-uni-patterns"
    - "-Wincomplete-record-updates"
    - "-Wredundant-constraints"
    - "-Wmissing-export-lists"
    - "-Wpartial-fields"
    - "-Wmissing-deriving-strategies"
    - "-Wunused-packages"
    # TODO extract a common list of exe dependencies
    dependencies:
    - pretty-simple
    - setlocale
    - docopt
    - bigtrees
    - unbounded-delays
    - silently
    - process
    - doctest-parallel
    - HUnit
    - MissingH
    - QuickCheck
    - attoparsec
    - base64-bytestring
