name:                bigtrees
description:         Performant hash trees to dedup large collections of files.
version:             0.7.1.0
author:              jefdaj
maintainer:          jefdaj@users.noreply.github.com
copyright:           "AGPL-3.0-only"

# TODO separate them out again?
dependencies:
- aeson
- aeson-pretty
- attoparsec
- base
- base64-bytestring
- bytestring
- case-insensitive
- crypton
- deepseq
- directory
- directory-tree
- docopt
- doctest-parallel
- file-io
- filepath
- filepath-bytestring
- knob
- hashable
- hashtables
- HUnit
- massiv
- MissingH
- monad-parallel
- os-string
- pretty-simple
- process
- QuickCheck
- quickcheck-instances
- quickcheck-unicode
- regex-tdfa
- safe-exceptions
- setlocale
- silently
- split
- streaming
- streaming-bytestring
- system-filepath
- tasty
- tasty-bench
- tasty-discover
- tasty-golden
- tasty-hspec
- tasty-hunit
- tasty-quickcheck
- temporary
- text
- th-utilities
- time
- unbounded-delays
- unix
- unix-compat
- unordered-containers
- utf8-string

# TODO which are really needed/helpful for which targets?
ghc-options:
- "-O2"
- "-threaded"
- "-rtsopts"
- "-with-rtsopts=-N"
- "-fwrite-ide-info"
- "-hiedir=.hie"
- "-Wall"
- "-Wcompat"
- "-Widentities"
- "-Wincomplete-uni-patterns"
- "-Wincomplete-record-updates"
- "-Wredundant-constraints"
- "-Wmissing-export-lists"
- "-Wpartial-fields"
- "-Wmissing-deriving-strategies"
- "-Wunused-packages"

library:
  source-dirs: lib
  exposed-modules:
  - System.Directory.BigTrees
  - System.Directory.BigTrees.DupeMap
  - System.Directory.BigTrees.HashTree
  - System.Directory.BigTrees.HashSet
  - System.Directory.BigTrees.HeadFoot
  - System.Directory.BigTrees.HashLine
  - System.Directory.BigTrees.Name
  - System.Directory.BigTrees.Util
  - System.Directory.BigTrees.Hash
  - System.Directory.BigTrees.Delta

executable:
  main: Main.hs
  source-dirs: app
  dependencies:
  - bigtrees

tests:

  test-lib:
    main: "Test.hs"
    source-dirs:
    - "lib"
    - "test/lib"
    dependencies:
    - bigtrees

  test-app:
    main: "Test.hs"
    source-dirs:
    - "app"
    - "test/app"
    dependencies:
    - bigtrees

  test-doctests:
    main: "doctest.hs"
    source-dirs:
    - "app"
    - "lib"
    - "test/doc"
    dependencies:
    - bigtrees

benchmarks:

  test-bench:
    main: "Bench.hs"
    source-dirs:
      - "lib"
      - "app"
      - "test/bench"
    dependencies:
      - bigtrees
    ghc-options:
      - "-with-rtsopts=-T"
      - "-fproc-alignment=64"
    # TODO how to get it to recognize these?
    # benchmark-arguments:
    #   - "--csv test/bench/bench.csv"
