name:                bigtrees
description:         Performant hash trees to dedup large collections of files.
version:             1.0.0.0
author:              jefdaj
maintainer:          jefdaj@users.noreply.github.com
copyright:           "AGPL-3.0-only"

# data-files:
#   - examples/*.sh
#   - examples/*.txt

library:
  source-dirs: lib
  exposed-modules:
  - System.Directory.BigTrees
  - System.Directory.BigTrees.DupeMap
  - System.Directory.BigTrees.HashTree
  - System.Directory.BigTrees.HashForest
  - System.Directory.BigTrees.HashLine
  - System.Directory.BigTrees.Name
  - System.Directory.BigTrees.Path
  - System.Directory.BigTrees.Hash
  - System.Directory.BigTrees.Delta
  # System.Directory.Tree
  dependencies:
  - Glob
  - HUnit
  - MissingH
  - QuickCheck
  - attoparsec
  - base
  - base64-bytestring
  - bytestring
  - crypton
  - deepseq
  - directory
  - directory-tree
  - filepath
  - hashable
  - hashtables
  - massiv
  - monad-parallel
  - quickcheck-instances
  - quickcheck-unicode
  - safe-exceptions
  - split
  - streaming
  - streaming-bytestring
  - system-filepath
  - tasty
  - tasty-discover
  - tasty-golden
  - tasty-hspec
  - tasty-hunit
  - tasty-quickcheck
  - temporary
  - text
  - th-utilities
  - unix
  - unordered-containers
  - utf8-string
 
executable:
  source-dirs: app
  main: Main.hs
  # TODO which of these options really help?
  ghc-options: "-Wall -O2 -threaded -rtsopts -with-rtsopts=-N -fwrite-ide-info"
  dependencies:
  - Glob
  - base
  - bigtrees
  - bytestring
  - docopt
  - filepath
  - pretty-simple
  - process
  - setlocale
  - silently
  - tasty
  - tasty-discover
  - tasty-golden
  - tasty-hspec
  - tasty-hunit
  - tasty-quickcheck
  - temporary
  - unbounded-delays
  - utf8-string

tests:

  test-lib:
    source-dirs:
    - "lib"
    - "test/lib"
    main: "Test.hs"
    # TODO which of these options really help?
    # ghc-options: "-Wall -O2 -threaded -rtsopts -with-rtsopts=-N -fwrite-ide-info"
    ghc-options:
    - "-O2"
    - "-threaded"
    - "-rtsopts"
    - "-with-rtsopts=-N"
    - "-fwrite-ide-info"
    - "-hiedir=.hie"
    - "-Wall"
    - "-Wcompat"
    - "-Widentities"
    - "-Wincomplete-uni-patterns"
    - "-Wincomplete-record-updates"
    - "-Wredundant-constraints"
    - "-Wmissing-export-lists"
    - "-Wpartial-fields"
    - "-Wmissing-deriving-strategies"
    - "-Wunused-packages"
    dependencies:
    - Glob
    - HUnit
    - MissingH
    - QuickCheck
    - attoparsec
    - base
    - base64-bytestring
    - bigtrees
    - bytestring
    - crypton
    - deepseq
    - directory
    - directory-tree
    - filepath
    - hashable
    - hashtables
    - massiv
    - monad-parallel
    - quickcheck-instances
    - safe-exceptions
    - split
    - streaming
    - streaming-bytestring
    - system-filepath
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - temporary
    - text
    - th-utilities
    - unix
    - unordered-containers
 
  test-app:
    source-dirs:
    - "test/app"
    - "app"
    main: "Test.hs"
    # TODO which of these options really help?
    # ghc-options: "-Wall -O2 -threaded -rtsopts -with-rtsopts=-N -fwrite-ide-info"
    ghc-options:
    - "-O2"
    - "-threaded"
    - "-rtsopts"
    - "-with-rtsopts=-N"
    - "-fwrite-ide-info"
    - "-hiedir=.hie"
    - "-Wall"
    - "-Wcompat"
    - "-Widentities"
    - "-Wincomplete-uni-patterns"
    - "-Wincomplete-record-updates"
    - "-Wredundant-constraints"
    - "-Wmissing-export-lists"
    - "-Wpartial-fields"
    - "-Wmissing-deriving-strategies"
    - "-Wunused-packages"
    # TODO extract a common list of exe dependencies
    dependencies:
    - Glob
    - base
    - bigtrees
    - bytestring
    - filepath
    - pretty-simple
    - process
    - silently
    - tasty
    - tasty-golden
    - temporary
    - unbounded-delays
    - utf8-string

  test-doctests:
    source-dirs:
    - "test/doc"
    - "lib"
    - "app"
    main: "doctest.hs"
    # TODO which of these options really help?
    # ghc-options: "-Wall -O2 -threaded -rtsopts -with-rtsopts=-N -fwrite-ide-info"
    ghc-options:
    - "-O2"
    - "-threaded"
    - "-rtsopts"
    - "-with-rtsopts=-N"
    - "-fwrite-ide-info"
    - "-hiedir=.hie"
    - "-Wall"
    - "-Wcompat"
    - "-Widentities"
    - "-Wincomplete-uni-patterns"
    - "-Wincomplete-record-updates"
    - "-Wredundant-constraints"
    - "-Wmissing-export-lists"
    - "-Wpartial-fields"
    - "-Wmissing-deriving-strategies"
    - "-Wunused-packages"
    # TODO extract a common list of exe dependencies
    dependencies:
    - Glob
    - HUnit
    - MissingH
    - QuickCheck
    - attoparsec
    - base
    - base64-bytestring
    - bigtrees
    - bytestring
    - crypton
    - deepseq
    - directory
    - directory-tree
    - doctest-parallel
    - filepath
    - hashable
    - hashtables
    - massiv
    - monad-parallel
    - pretty-simple
    - process
    - quickcheck-instances
    - safe-exceptions
    - silently
    - split
    - streaming
    - streaming-bytestring
    - system-filepath
    - tasty
    - tasty-golden
    - temporary
    - text
    - th-utilities
    - unbounded-delays
    - unix
    - unordered-containers
    - utf8-string
