recommend-stack-upgrade: false

packages:
  - ./directory-tree
  - .

# TODO does this help?
nix:
  enable: false
  pure: false

# for weeder
# does this also have to be added to each target in package.yaml?
ghc-options:
  "$locals": -fwrite-ide-info

# Latest LTS for ghc948, which is the latest GHC with a working static nix build as of 2024-06-19
# Because it's getting old, it needs a few custom packages + flags etc (below) to enable os-string.
resolver: lts-21.25

extra-deps:
  - docopt-0.7.0.8
  - os-string-2.0.3
  - hashable-1.4.6.0
  - directory-1.3.8.2
  - filepath-1.5.2.0
  - file-io-0.1.1
  - process-1.6.20.0
  - Cabal-syntax-3.10.3.0
  - Cabal-3.10.3.0
  - unix-2.8.5.1

allow-newer: true

allow-newer-deps:
  - MissingH
  - directory
  - file-io
  - hashable
  - unix

flags:
  unix:
    os-string: true
  file-io:
    os-string: true
  directory:
    os-string: true
