recommend-stack-upgrade: false

# TODO update directory-tree code too if it has any new work
packages:
  - ./directory-tree
  - .

# All the Nix integration business happens in the nix flake;
# by the time we run (Nix-wrapped) stack it shouldn't have to do anything.
# TODO test whether this works independently of Nix on a regular Linux machine.
notify-if-nix-on-path: false
nix:
  enable: false
  pure: false

# for weeder
# does this also have to be added to each target in package.yaml?
ghc-options:
  "$locals": -fwrite-ide-info

# GHC 9.8.4, which should match the version in flake.nix
resolver: lts-23.26

extra-deps:
  - directory-1.3.8.5
  - unix-2.8.6.0
  - file-io-0.1.5
  - filepath-1.5.4.0
  - process-1.6.25.0
  - filepath-bytestring-1.5.2.0.2@sha256:d410c6e273c926411a9b35009e8c25ef8fe522c49fa6c226365a20dceb96b6e7,3183

allow-newer: true

allow-newer-deps:
  # - unix

flags:
  unix:
    os-string: true
  file-io:
    os-string: true
  directory:
    os-string: true
