recommend-stack-upgrade: false
resolver: lts-22.16
packages:
  - .

# for weeder
# note that this also has to be added to each target in package.yaml?
ghc-options:
  "$locals": -fwrite-ide-info

extra-deps:
  - docopt-0.7.0.8@sha256:b88ca348766430101ff1d1ca230ea9038a9fcd63aa3f042a4b95ceab207357e5,3352
