# TODO should this be true? seems important for a library
type-class-roots = false

unused-types = true

roots = [

  "^Main.main$",
  "^Paths_bigtrees.*",

  # tasty-discover tests
  "^*.prop_*",
  "^*.scprop_*",
  "^*.hprop_*",
  "^*.unit_*",
  "^*.spec_*",
  "^*.test_*",
  "^*.tasty_*",

]

root-instances = [

  # ignore this to minimize diff with upstream
  { module = "^System.Directory.Tree$" }

]
